source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyCoreData_Example', :exclusive => true do
  pod "EasyCoreData", :path => "../"
end

target 'EasyCoreData_Tests', :exclusive => true do
  pod "EasyCoreData", :path => "../"

  
end
